Remove DeadRelation in favor of empty relations
Instead of treating dead relations as a separate type, handle missing
relation errors more consistently and just treat them as not having any
remove members or data.

diff --git a/test/bin/relation-list b/test/bin/relation-list
--- a/test/bin/relation-list
+++ b/test/bin/relation-list
@@ -1,11 +1,16 @@
 #!/bin/bash
 
+fail_not_found() {
+    1>&2 echo "ERROR invalid value \"$1\" for option -r: relation not found"
+    exit 2
+}
+
 case $2 in
     1) echo '["remote/0"]' ;;
     2) echo '["remote/0"]' ;;
-    3) exit 2 ;;
+    3) fail_not_found $2 ;;
     4) echo '["remoteapp1/0"]' ;;
     5) echo '["remoteapp1/0"]' ;;
     6) echo '["remoteapp2/0"]' ;;
-    *) exit 2 ;;
+    *) fail_not_found $2 ;;
 esac
