Handle uv.lock rather than requirements.txt.

diff --git a/.github/workflows/published-charms-tests.yaml b/.github/workflows/published-charms-tests.yaml
--- a/.github/workflows/published-charms-tests.yaml
+++ b/.github/workflows/published-charms-tests.yaml
@@ -147,7 +147,6 @@ jobs:
         run: charmcraft init --profile=${{ matrix.profile }} --author=charm-tech
 
       - name: Install dependencies
-        id: deps
         run: pip install tox~=4.2 uv~=0.9 tox-uv~=1.29
 
       - name: Update 'ops' and 'ops-scenario' dependencies in test charm to latest
@@ -158,19 +157,26 @@ jobs:
             echo -e "\ngit+$GITHUB_SERVER_URL/$GITHUB_REPOSITORY@$GITHUB_SHA#egg=ops" >> requirements.txt
             echo -e "\ngit+$GITHUB_SERVER_URL/$GITHUB_REPOSITORY@$GITHUB_SHA#egg=ops-scenario&subdirectory=testing" >> requirements.txt
           fi
+          if [ -e "uv.lock" ]; then
+            uv remove ops --optional unit --frozen
+            uv remove ops-scenario --optional unit --frozen
+            uv remove ops --frozen
+            uv add git+$GITHUB_SERVER_URL/$GITHUB_REPOSITORY@$GITHUB_SHA#subdirectory=testing --optional unit --raw-sources --prerelease=if-necessary-or-explicit
+            uv add git+$GITHUB_SERVER_URL/$GITHUB_REPOSITORY@$GITHUB_SHA --raw-sources --prerelease=if-necessary-or-explicit
+          else
+            echo "Error: no uv.lock file found"
+            exit 1
+          fi
 
       - name: Run the charm's unit tests
-        if: ${{ !cancelled() && steps.deps.outcome == 'success' }}
         run: tox -vve unit
 
       - name: Run the charm's lint tests
-        if: ${{ !cancelled() && steps.deps.outcome == 'success' }}
         run: tox -vve lint
 
       # Charmcraft 4 doesn't have a separate 'static' environment.
       - name: Check for tox static environment
         id: has-static
-        if: ${{ !cancelled() && steps.deps.outcome == 'success' }}
         run: |
           if tox list --no-desc | grep '^static$'; then
             echo 'static_exists=true' >> "$GITHUB_OUTPUT"
@@ -179,5 +185,5 @@ jobs:
           fi
 
       - name: Run the charm's static tests
-        if: ${{ !cancelled() && steps.deps.outcome == 'success' && steps.has-static.outputs.static_exists == 'true' }}
+        if: ${{ steps.has-static.outputs.static_exists == 'true' }}
         run: tox -vve static
